#!/bin/bash
# dsh-chrome-bridge installer (idempotent — safe to re-run)
#
#   ./install.sh              install / update
#   ./install.sh --uninstall  remove everything except the Chrome extension itself
#
# What it does:
#   1. copies the extension + native host into ~/.dsh/chrome-bridge/ (repo can move afterwards)
#   2. registers the native messaging host with Chrome, bound to the extension's fixed ID
#   3. installs the `cb` CLI, the `dsh-chrome-bridge` manager, and the DSH skill
#
# The extension ID is derived from the public key embedded in extension/manifest.json,
# so it is the same on every machine — the registration file never needs editing.

set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"
BRIDGE="$HOME/.dsh/chrome-bridge"
# The extension lives in a VISIBLE folder on purpose: Chrome's "Load unpacked" file
# picker cannot reach hidden directories without ⌘⇧G.
EXT_DIR="$HOME/dsh-bridge-extension"
HOST_NAME="com.dsh.bridge"
NM_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
NM_FILE="$NM_DIR/$HOST_NAME.json"

if [ "${1:-}" = "--uninstall" ]; then
  rm -f "$NM_FILE"
  rm -f /tmp/dsh-bridge.sock /tmp/dsh-bridge.token /tmp/dsh-bridge.log
  rm -rf "$BRIDGE" "$EXT_DIR"
  rm -f "$HOME/.dsh/bin/cb" "$HOME/.dsh/bin/dsh-chrome-bridge"
  rm -rf "$HOME/.dsh/skills/browser"
  echo "Removed: native host registration, host dir, extension dir, cb, manager, skill."
  echo "The Chrome extension itself must be removed at chrome://extensions (Chrome Bridge)."
  exit 0
fi

# ── prerequisites ───────────────────────────────────────────────────────────
if [ "$(uname)" != "Darwin" ]; then
  echo "This bridge is macOS-only for now (the native messaging path is macOS-specific)." >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required (used to derive the extension ID from the manifest key)." >&2
  exit 1
fi
NODE_BIN=""
for N in "${DSH_BRIDGE_NODE:-}" /usr/local/bin/node "$HOME/.local/bin/node" /opt/homebrew/bin/node; do
  if [ -n "$N" ] && [ -x "$N" ]; then NODE_BIN="$N"; break; fi
done
if [ -z "$NODE_BIN" ]; then
  echo "node not found. Install Node.js, or point DSH_BRIDGE_NODE at its absolute path." >&2
  exit 1
fi

echo "==> 1/6 native host -> $BRIDGE"
mkdir -p "$BRIDGE/host" "$EXT_DIR" "$HOME/.dsh/bin" "$HOME/.dsh/chrome-cursor"
cp -R "$REPO/extension/." "$EXT_DIR/"
cp "$REPO/host/host.js" "$REPO/host/run.sh" "$BRIDGE/host/"
cp "$REPO/scratch/in-page-cursor.js" "$HOME/.dsh/chrome-cursor/in-page-cursor.js" 2>/dev/null || true
chmod +x "$BRIDGE/host/run.sh"

echo "==> 2/6 extension ID (derived from the manifest key; fixed forever)"
EXT_ID="$(python3 - "$EXT_DIR/manifest.json" <<'PY'
import base64, hashlib, json, sys
key = json.load(open(sys.argv[1]))["key"]
der = base64.b64decode(key)
h = hashlib.sha256(der).hexdigest()[:32]
print("".join(chr(ord("a") + int(c, 16)) for c in h))
PY
)"
echo "    $EXT_ID"

echo "==> 3/6 register native messaging host"
mkdir -p "$NM_DIR"
cat > "$NM_FILE" <<JSON
{
  "name": "$HOST_NAME",
  "description": "dsh-chrome-bridge native host (local browser control)",
  "path": "$BRIDGE/host/run.sh",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
JSON
echo "    $NM_FILE"

echo "==> 4/6 install the cb CLI"
cp "$REPO/bin/cb" "$HOME/.dsh/bin/cb"
chmod +x "$HOME/.dsh/bin/cb"

echo "==> 5/6 install the manager command"
cat > "$HOME/.dsh/bin/dsh-chrome-bridge" <<SH
#!/bin/sh
# generated by install.sh — points back at the checkout
exec "$REPO/bridge" "\$@"
SH
chmod +x "$HOME/.dsh/bin/dsh-chrome-bridge"

echo "==> 6/6 install the DSH skill"
mkdir -p "$HOME/.dsh/skills/browser"
cp "$REPO/skill/SKILL.md" "$HOME/.dsh/skills/browser/SKILL.md"
echo "    ~/.dsh/skills/browser/SKILL.md"

cat <<EOF

Done. One manual step left — you only ever do this once:

  1. open chrome://extensions
  2. turn on "Developer mode" (top right)
  3. click "Load unpacked" and pick this folder:

     $EXT_DIR

  4. no buttons to press afterwards. Verify with:  cb status

Optional — native DSH tools (browser_* instead of shelling out to cb):
  DSH sidebar -> Plugins -> Add plugin -> paste this folder:

     $REPO/plugin

  then restart DSH (a freshly installed bundle is not hot-loaded).

Extension ID: $EXT_ID (already bound in the native host registration)
EOF
